#!/bin/bash

read -r -p 'Commit message: ' desc
echo
git add .
git add -u
git commit -m "$desc"
git push origin master
expect "Username for 'https://github.com':"
send 'puriabestia@gmail.com'
expect "Password for 'https://github.com':"
send 'H5q95u59!'
